openapi: 3.1.0
info:
  title: Ambulance Dispatch Mock API
  version: 1.0.0
paths:
  /dispatch:
    post:
      summary: Dispatch an ambulance
      operationId: dispatchAmbulance
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                location:
                  type: string
                  description: The location to dispatch the ambulance to.
                injury:
                  type: string
                  description: Description of the injury or emergency.
      responses:
        200:
          description: Dispatch confirmation
          content:
            application/json:
              schema:
                type: object
                properties:
                  eta:
                    type: number
                    description: Estimated time of arrival in minutes.
                  dispatch_id:
                    type: string
                    description: Unique identifier for the dispatch.
